language: python
python:
- '3.6'
cache: pip
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y enchant
install: pip install -U -r requirements.txt
script:
- pytest
- python setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: QTKkILYDnaGgVJjArwfqeZ21ZIcKvpA544kSQxroaBWvAP7QQNVT9bvZBQ+rX0uYPn7xEfk+jsVIV+SGqzCp04FJa3pZM1HXCUgRU57GKoARG2hLkhtSPAsmvVhr/+rp40ja3obpAQMgAR2mRdz39JBg2eY2CbM7IOwVf3DFecVBuMB1SAgLkvcLCpLGOKWUjQ9PIXgHxUg3/SDUYhx7xfboirgbzNACZAWxg3YlnzclTp4o6Wl4aaQUWH4m8GEjYxANdlIpgfWTGtHVuAUKbS4clW6PvcvxbgPyRKaOR8rnJ+U7cKt1rtFycy9puwErttgaZbmzi9dpUJIGyeX3NQkO6OMFZpO7PYWOvrlO1XdVHB89gY+B9oBGDcKIUEAwNdqkyu9aaSz+XOWaTgT3D7XzztaBCTdN09j+jBJAID0iGbjSW82Nit76R7cDDEnoi3L/2GPss2nXz9JaOsbvTkpnyiUHdveJUTwJfMJYxXYGAGKuMXUBsalPwzIA8IM65kL6H6gcL4dhPBM56V+VYHKOzYXwqWkTrx5FFKzDxg3dH89VKZsI8pSCYXPqPRngIxdVWXNBQKcwT05ng4k8zOA9nnGhYrKPkBVSqerPTi906CYeBg5GvBIQP7v3J+PUhOyCImfHMekfxrB4NemzVD+0j77F1d1hNYON7hjBj5c=
  file: dist/*.whl
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
