version: '2'

networks:
    saapy:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/16
                  gateway: 172.16.0.1

volumes:
